"""update_application_education_schema

Revision ID: e7e83f787972
Revises: 7706420ce836
Create Date: 2026-08-25 00:55:44.355493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e83f787972'
down_revision: Union[str, None] = '7706420ce836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_education', sa.Column('board', sa.String(length=100), nullable=True))
    op.add_column('application_education', sa.Column('stream', sa.String(length=50), nullable=True))
    op.alter_column('application_education', 'degree',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('application_education', 'level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application_education', 'level',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('application_education', 'degree',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('application_education', 'stream')
    op.drop_column('application_education', 'board')
    # ### end Alembic commands ###
