"""add_application_end_date_to_jobs

Revision ID: 9a2e4905c4ae
Revises: e7e83f787972
Create Date: 2026-08-25 02:01:43.628946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2e4905c4ae'
down_revision: Union[str, None] = 'e7e83f787972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('application_end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'application_end_date')
    # ### end Alembic commands ###
