"""update_education_schema

Revision ID: 7706420ce836
Revises: 86ccf2e6a2ed
Create Date: 2026-08-24 23:46:46.320280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7706420ce836'
down_revision: Union[str, None] = '86ccf2e6a2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new enum values to Postgres educationlevel enum
    op.execute("ALTER TYPE educationlevel ADD VALUE IF NOT EXISTS 'SECONDARY_SCHOOL'")
    op.execute("ALTER TYPE educationlevel ADD VALUE IF NOT EXISTS 'HIGHER_SECONDARY'")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('board', sa.String(length=100), nullable=True))
    op.add_column('education', sa.Column('stream', sa.String(length=50), nullable=True))
    op.alter_column('education', 'degree',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('education', 'degree',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('education', 'stream')
    op.drop_column('education', 'board')
    # ### end Alembic commands ###
